### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by ergodicbreak** [pedrozath/coltrane#57]
I just found this project today and I think it's great, however it seems a bit abandoned (the chat doesn't work for example and some of the links in the readme are 404, open PRs, etc). 

I was using it to find chords and it also seems to lack some results that the other online chord finders have. I'd like to contribute but does anyone know what the status of this project is? Finished? On hold?

**Comment by pedrozath** [comment]
Thanks for the interest in the project.

It might feel a little abandoned, since I'm mostly the sole contributor, and I've been focusing on another projects, but it's not completely. I still check this from time to time and can perform PR reviews, fix some issues and even implement from new features.

Also thanks for reminding me about the readme being outdated. Later. when I have some time, I'll create a discord server and link it there.

If you can please open an issue describing the chord you expected, and the input, I would really appreciate.
